# Generated by Django 6.0.2 on 2026-03-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('photo', models.ImageField(upload_to='images', verbose_name='Photo')),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('count_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog Article',
                'verbose_name_plural': 'Blog Articles',
            },
        ),
    ]
