# Generated by Django 6.0.2 on 2026-03-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogarticle',
            old_name='count_views',
            new_name='views',
        ),
    ]
