# Generated by Django 6.0.2 on 2026-03-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogarticle',
            old_name='count_views',
            new_name='views',
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is published'),
        ),
    ]
