# Generated by Django 6.0.2 on 2026-03-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_count_views_blogarticle_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is published'),
        ),
    ]
